### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by yic23** [DanielRuf/font-squirrel-downloader#3]
Hi, I am completely clueless in programming stuff. I am a designer. How do I use this? @DanielRuf ping

**Comment by DanielRuf** [comment]
Hi @yic23,

First you have to install NodeJS.

You can get the installer for your OS from https://nodejs.org/en/download/

Then you have to follow the install step from the readme for npm.

After this run `font-squirrel-downloader` from a shell (cmd, bash, ...).

**Comment by yic23** [comment]
> 
> 
> Hi @yic23,
> 
> First you have to install NodeJS.
> 
> You can get the installer for your OS from https://nodejs.org/en/download/
> 
> Then you have to follow the install step from the readme for npm.
> 
> After this run `font-squirrel-downloader` from a shell (cmd, bash, ...).

Hi Daniel, thanks! I installed NoseJS. However, I am afraid I am still not knowledgable enough and I must be missing something. I get errors trying to run the script from the readme in cmd. I first tried the first line, than both at the same time, got errors. [https://imgur.com/a/9tGrevK](url)

**Comment by DanielRuf** [comment]
Ah you also have to install Git as it is directly cloned using `git` as I do not host this on npmjs.com for several reasons.

Alternatively you can install the 1.0.7 release from npmjs running `npm i -g font-squirrel-downloader`.

https://www.npmjs.com/package/font-squirrel-downloader

**Comment by DanielRuf** [comment]
The latest version is 1.1.0 and brings some improvements like skipping already downloaded fontface kits.

See https://github.com/DanielRuf/font-squirrel-downloader/commits/master for all changes.

**Comment by yic23** [comment]
Ok, I typed `npm i -g font-squirrel-downloader` in cmd and then the usage command from the readme. This is what I get: https://imgur.com/a/nQlJ53X. 
Seems to be working, though I am not sure how to get v1.1.0. A bunch of zip folders that are inaccessible are showing up in my user folder.

**Comment by DanielRuf** [comment]
You can install Git using an installer from https://git-scm.com/downloads

Or you can also alternatively look for the path where the package was installed to and replace the files in there with the new ones from the repository.

https://github.com/DanielRuf/font-squirrel-downloader/archive/master.zip

You may have to update only the index.js and package.json files.

**Comment by DanielRuf** [comment]
> Or you can also alternatively look for the path where the package was installed to

Should be at `C:\Users\Yam\AppData\Roaming\npm\node_modules\font-squirrel-downloader`.

Not sure why so many try to hide their username in screenshots but this is no critical information and often just security by obscurity (a Windows Powershell / CMD / NodeJS command can easily retrieve this very easily).

**Comment by yic23** [comment]
Ok, installed GIT and replaced the files to update to 1.1.0. 

Re username, not sure, just thought it was wise. How did you find mine? haha.

**Comment by yic23** [comment]
Also, got this error part way through. Then typed in the command again and completed successfully. https://imgur.com/a/NUJhuD5

**Comment by DanielRuf** [comment]
> Re username, not sure, just thought it was wise. How did you find mine

You forgot to replace it in one line. Nothing critical.

> Is there a way to set the destination directory for the downloads?

No, the files are downloaded to the directory where the command is executed, the current working directory.

https://github.com/DanielRuf/font-squirrel-downloader/blob/master/index.js#L73

If you need this feature please create a new issue about it so we can track and implement this feature request.

Otherwise I might lose the overview here (keep different things separated in different issues).

> Can the command be run every so often to download any additions on the site?

Yes, existing files are skipped and missing files are downloaded.

https://github.com/DanielRuf/font-squirrel-downloader/blob/master/index.js#L35-L42


> Also, got this error part way through. Then typed in the command again and completed successfully.
https://bgp.he.net/dns/fontsquirrel.com#_ipinfo

This is the IP of fontsquirrel. It seems there was some network related issue (connection timed out).

I can catch this error and reject the promise and cancel the download(s) this way. But I do not have control of the connectivity to this website.

**Comment by DanielRuf** [comment]
> Re username, not sure, just thought it was wise. How did you find mine

You forgot to replace it in one line. Nothing critical.

> Is there a way to set the destination directory for the downloads?

No, the files are downloaded to the directory where the command is executed, the current working directory.

https://github.com/DanielRuf/font-squirrel-downloader/blob/master/index.js#L73

If you need this feature please create a new issue about it so we can track and implement this feature request.

Otherwise I might lose the overview here (keep different things separated in different issues).

> Can the command be run every so often to download any additions on the site?

Yes, existing files are skipped and missing files are downloaded.

https://github.com/DanielRuf/font-squirrel-downloader/blob/master/index.js#L35-L42


> Also, got this error part way through. Then typed in the command again and completed successfully.
https://bgp.he.net/dns/fontsquirrel.com#_ipinfo

This is the IP of fontsquirrel. It seems there was some network related issue (connection timed out).

I can catch this error. But I do not have control of the connectivity to this website.

See https://github.com/DanielRuf/font-squirrel-downloader/issues/4

**Comment by yic23** [comment]
Thanks. So is there a way to change the current working directory to another? Reason is I now have 900 odd font zips in my user folder and it would be good to have it at least in a subfolder called "FontSquirrel". It will make it easier to update. I will create another issue for it.

**Comment by DanielRuf** [comment]
> So is there a way to change the current working directory to another?

Sure, `cd` to the desired directory / path and run `font-squirrel-downloader` there, it is globally installed and can be invoked from everywhere.

**Comment by DanielRuf** [comment]
```shell
mkdir FontSquirrel
cd FontSquirrel
font-squirrel-downloader
```

**Comment by DanielRuf** [comment]
Hi @yic23,

this is now implemented in v1.2.0.
See https://github.com/DanielRuf/font-squirrel-downloader/commit/bc2eb4c64798384ff271634b3503af84e83c6599

Does `font-squirrel-downloader` work for you know and are your questions answered?

**Comment by DanielRuf** [comment]
Closing as I did not receive any further feedback.

Let me know if your questions are answered or if there are still issues.

**Comment by DanielRuf** [comment]
Closing as I did not receive any further feedback.

Let me know if your questions are answered or if there are still issues.
